//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesForceBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesForceBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required argument is missing ähnelt.
        /// </summary>
        internal static string ConfigurationArgumentMissing {
            get {
                return ResourceManager.GetString("ConfigurationArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument missing for {0} value ähnelt.
        /// </summary>
        internal static string ConfigurationArgumentValueMissing {
            get {
                return ResourceManager.GetString("ConfigurationArgumentValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified destination is invalid. Use &apos;FileSystem&apos;, &apos;Azure&apos;, &apos;AWS&apos; ähnelt.
        /// </summary>
        internal static string ConfigurationInvalidUploader {
            get {
                return ResourceManager.GetString("ConfigurationInvalidUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run &apos;{0} --help&apos; to display help ähnelt.
        /// </summary>
        internal static string ConfigurationProblemCallHelp {
            get {
                return ResourceManager.GetString("ConfigurationProblemCallHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check the provided AWS Credentials ähnelt.
        /// </summary>
        internal static string ConfigurationS3Credentials {
            get {
                return ResourceManager.GetString("ConfigurationS3Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to login at Salesforce. Please check your credentials. ähnelt.
        /// </summary>
        internal static string ConfigurationSfdcCredentialsInvalid {
            get {
                return ResourceManager.GetString("ConfigurationSfdcCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error uploading the file to Azure: {0} ähnelt.
        /// </summary>
        internal static string StatusAzureUploadFailed {
            get {
                return ResourceManager.GetString("StatusAzureUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting to SalesForce.com ...  ähnelt.
        /// </summary>
        internal static string StatusConnectingToSalesforce {
            get {
                return ResourceManager.GetString("StatusConnectingToSalesforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading {0} of {1}: {2} ...  ähnelt.
        /// </summary>
        internal static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting list of export files ...  ähnelt.
        /// </summary>
        internal static string StatusFilePage {
            get {
                return ResourceManager.GetString("StatusFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ({0} files to download) ähnelt.
        /// </summary>
        internal static string StatusFilePageResult {
            get {
                return ResourceManager.GetString("StatusFilePageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  (1 file to download) ähnelt.
        /// </summary>
        internal static string StatusFilePageResultSingular {
            get {
                return ResourceManager.GetString("StatusFilePageResultSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading Settings... ähnelt.
        /// </summary>
        internal static string StatusReadSettings {
            get {
                return ResourceManager.GetString("StatusReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to upload file to S3: {0} ähnelt.
        /// </summary>
        internal static string StatusS3UploadFailed {
            get {
                return ResourceManager.GetString("StatusS3UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting backup... ähnelt.
        /// </summary>
        internal static string StatusStartBackup {
            get {
                return ResourceManager.GetString("StatusStartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error occured ähnelt.
        /// </summary>
        internal static string StatusUnknownError {
            get {
                return ResourceManager.GetString("StatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading {0} to Azure ...  ähnelt.
        /// </summary>
        internal static string StatusUploadingAzure {
            get {
                return ResourceManager.GetString("StatusUploadingAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading {0} to AWS S3 ...  ähnelt.
        /// </summary>
        internal static string StatusUploadingS3 {
            get {
                return ResourceManager.GetString("StatusUploadingS3", resourceCulture);
            }
        }
    }
}
